### PR TITLE
Bson datetime support

### PR DESCRIPTION
**Pull request by SlyngDK**
Hi

I have added support for serializing Circe Json {"$date":1563724806000} to BsonDateTime.

I had problems building on travis with oraclejdk8, so I change to openjdk8.
https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766

### CODE REVIEW

**Comment by SlyngDK** [comment]
Hi @travisbrown 
I have added support BSONDateTime, but there is a breaking change on parsing BSONDateTime.
This change is more correct, when working with mongodb.

What do you think of these changes??
Is it something you will consider merging??

**Comment by travisbrown** [comment]
Thanks! Are you interested in maintaining this library? I can still handle releases, but I’m not currently using it and don’t have a lot of time for review, so if someone wants to take over everything else that’d be much appreciated.

**Comment by SlyngDK** [comment]
If you need a maintainer, to have someone doing reviews, merge and etc. I can try help with that.

**Comment by SlyngDK** [comment]
@travisbrown ^^^^

**Comment by travisbrown** [comment]
@SlyngDK I've added you to the project. Feel free to merge this when it's green. Let me know when you're ready for a release / have a draft of release notes. Thanks!

**Pull request merged**
