### PR TITLE
replace reactivemongo.bson with reactivemongo.api.bson

### PR DESCRIPTION
**Pull request by arch89**

### CODE REVIEW

**Comment by travisbrown** [comment]
Thanks, but can you separate out the changes? The traversal logic is definitely unrelated, right, and I'm not sure about the `HandlerException`?

**Comment by arch89** [comment]
I'm not quite sure, that i understand you correctly, but it's related, because there is no more unapply method to stream, only seq.
According to code comments, HandlerException - is "Exception from a BSON reader/writer", seems legit for using here. Should i use TypeDoesNotMatchException(non-customizable error message) instead?

**Comment by travisbrown** [comment]
Okay, thanks, I'll take a closer look today.

**Comment by travisbrown** [comment]
I'm going to go ahead and merge this, although I still don't have a lot of context about the `api` changes in ReactiveMongo. By the way if someone wants to take over maintenance of this project, please let me know.

**Pull request merged**
